version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /simutartor.wdl
    testParameterFiles:
      - /simutartor.json
    authors:
      - orcid: 0000-0003-4896-1858
    name: simutartor